# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/dron/Рабочий стол/bachelor/compiler"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/dron/Рабочий стол/bachelor/compiler"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/dron/Рабочий стол/bachelor/compiler/CMakeFiles" "/home/dron/Рабочий стол/bachelor/compiler/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/dron/Рабочий стол/bachelor/compiler/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

lib/default.o: lib/default.c.o

.PHONY : lib/default.o

# target to build an object file
lib/default.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/default.c.o
.PHONY : lib/default.c.o

lib/default.i: lib/default.c.i

.PHONY : lib/default.i

# target to preprocess a source file
lib/default.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/default.c.i
.PHONY : lib/default.c.i

lib/default.s: lib/default.c.s

.PHONY : lib/default.s

# target to generate assembly for a file
lib/default.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/default.c.s
.PHONY : lib/default.c.s

lib/locks/atomics.o: lib/locks/atomics.c.o

.PHONY : lib/locks/atomics.o

# target to build an object file
lib/locks/atomics.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/atomics.c.o
.PHONY : lib/locks/atomics.c.o

lib/locks/atomics.i: lib/locks/atomics.c.i

.PHONY : lib/locks/atomics.i

# target to preprocess a source file
lib/locks/atomics.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/atomics.c.i
.PHONY : lib/locks/atomics.c.i

lib/locks/atomics.s: lib/locks/atomics.c.s

.PHONY : lib/locks/atomics.s

# target to generate assembly for a file
lib/locks/atomics.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/atomics.c.s
.PHONY : lib/locks/atomics.c.s

lib/locks/spinlock.o: lib/locks/spinlock.c.o

.PHONY : lib/locks/spinlock.o

# target to build an object file
lib/locks/spinlock.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/spinlock.c.o
.PHONY : lib/locks/spinlock.c.o

lib/locks/spinlock.i: lib/locks/spinlock.c.i

.PHONY : lib/locks/spinlock.i

# target to preprocess a source file
lib/locks/spinlock.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/spinlock.c.i
.PHONY : lib/locks/spinlock.c.i

lib/locks/spinlock.s: lib/locks/spinlock.c.s

.PHONY : lib/locks/spinlock.s

# target to generate assembly for a file
lib/locks/spinlock.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/spinlock.c.s
.PHONY : lib/locks/spinlock.c.s

lib/locks/wait_group.o: lib/locks/wait_group.c.o

.PHONY : lib/locks/wait_group.o

# target to build an object file
lib/locks/wait_group.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/wait_group.c.o
.PHONY : lib/locks/wait_group.c.o

lib/locks/wait_group.i: lib/locks/wait_group.c.i

.PHONY : lib/locks/wait_group.i

# target to preprocess a source file
lib/locks/wait_group.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/wait_group.c.i
.PHONY : lib/locks/wait_group.c.i

lib/locks/wait_group.s: lib/locks/wait_group.c.s

.PHONY : lib/locks/wait_group.s

# target to generate assembly for a file
lib/locks/wait_group.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/locks/wait_group.c.s
.PHONY : lib/locks/wait_group.c.s

lib/root_lib.o: lib/root_lib.c.o

.PHONY : lib/root_lib.o

# target to build an object file
lib/root_lib.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/root_lib.c.o
.PHONY : lib/root_lib.c.o

lib/root_lib.i: lib/root_lib.c.i

.PHONY : lib/root_lib.i

# target to preprocess a source file
lib/root_lib.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/root_lib.c.i
.PHONY : lib/root_lib.c.i

lib/root_lib.s: lib/root_lib.c.s

.PHONY : lib/root_lib.s

# target to generate assembly for a file
lib/root_lib.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/root_lib.c.s
.PHONY : lib/root_lib.c.s

lib/scheduler/context.o: lib/scheduler/context.c.o

.PHONY : lib/scheduler/context.o

# target to build an object file
lib/scheduler/context.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/context.c.o
.PHONY : lib/scheduler/context.c.o

lib/scheduler/context.i: lib/scheduler/context.c.i

.PHONY : lib/scheduler/context.i

# target to preprocess a source file
lib/scheduler/context.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/context.c.i
.PHONY : lib/scheduler/context.c.i

lib/scheduler/context.s: lib/scheduler/context.c.s

.PHONY : lib/scheduler/context.s

# target to generate assembly for a file
lib/scheduler/context.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/context.c.s
.PHONY : lib/scheduler/context.c.s

lib/scheduler/coroutine.o: lib/scheduler/coroutine.c.o

.PHONY : lib/scheduler/coroutine.o

# target to build an object file
lib/scheduler/coroutine.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/coroutine.c.o
.PHONY : lib/scheduler/coroutine.c.o

lib/scheduler/coroutine.i: lib/scheduler/coroutine.c.i

.PHONY : lib/scheduler/coroutine.i

# target to preprocess a source file
lib/scheduler/coroutine.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/coroutine.c.i
.PHONY : lib/scheduler/coroutine.c.i

lib/scheduler/coroutine.s: lib/scheduler/coroutine.c.s

.PHONY : lib/scheduler/coroutine.s

# target to generate assembly for a file
lib/scheduler/coroutine.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/coroutine.c.s
.PHONY : lib/scheduler/coroutine.c.s

lib/scheduler/fiber.o: lib/scheduler/fiber.c.o

.PHONY : lib/scheduler/fiber.o

# target to build an object file
lib/scheduler/fiber.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/fiber.c.o
.PHONY : lib/scheduler/fiber.c.o

lib/scheduler/fiber.i: lib/scheduler/fiber.c.i

.PHONY : lib/scheduler/fiber.i

# target to preprocess a source file
lib/scheduler/fiber.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/fiber.c.i
.PHONY : lib/scheduler/fiber.c.i

lib/scheduler/fiber.s: lib/scheduler/fiber.c.s

.PHONY : lib/scheduler/fiber.s

# target to generate assembly for a file
lib/scheduler/fiber.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/fiber.c.s
.PHONY : lib/scheduler/fiber.c.s

lib/scheduler/local_queues_with_steal_scheduler.o: lib/scheduler/local_queues_with_steal_scheduler.c.o

.PHONY : lib/scheduler/local_queues_with_steal_scheduler.o

# target to build an object file
lib/scheduler/local_queues_with_steal_scheduler.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/local_queues_with_steal_scheduler.c.o
.PHONY : lib/scheduler/local_queues_with_steal_scheduler.c.o

lib/scheduler/local_queues_with_steal_scheduler.i: lib/scheduler/local_queues_with_steal_scheduler.c.i

.PHONY : lib/scheduler/local_queues_with_steal_scheduler.i

# target to preprocess a source file
lib/scheduler/local_queues_with_steal_scheduler.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/local_queues_with_steal_scheduler.c.i
.PHONY : lib/scheduler/local_queues_with_steal_scheduler.c.i

lib/scheduler/local_queues_with_steal_scheduler.s: lib/scheduler/local_queues_with_steal_scheduler.c.s

.PHONY : lib/scheduler/local_queues_with_steal_scheduler.s

# target to generate assembly for a file
lib/scheduler/local_queues_with_steal_scheduler.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/local_queues_with_steal_scheduler.c.s
.PHONY : lib/scheduler/local_queues_with_steal_scheduler.c.s

lib/scheduler/manager.o: lib/scheduler/manager.c.o

.PHONY : lib/scheduler/manager.o

# target to build an object file
lib/scheduler/manager.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/manager.c.o
.PHONY : lib/scheduler/manager.c.o

lib/scheduler/manager.i: lib/scheduler/manager.c.i

.PHONY : lib/scheduler/manager.i

# target to preprocess a source file
lib/scheduler/manager.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/manager.c.i
.PHONY : lib/scheduler/manager.c.i

lib/scheduler/manager.s: lib/scheduler/manager.c.s

.PHONY : lib/scheduler/manager.s

# target to generate assembly for a file
lib/scheduler/manager.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/manager.c.s
.PHONY : lib/scheduler/manager.c.s

lib/scheduler/scheduler.o: lib/scheduler/scheduler.c.o

.PHONY : lib/scheduler/scheduler.o

# target to build an object file
lib/scheduler/scheduler.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/scheduler.c.o
.PHONY : lib/scheduler/scheduler.c.o

lib/scheduler/scheduler.i: lib/scheduler/scheduler.c.i

.PHONY : lib/scheduler/scheduler.i

# target to preprocess a source file
lib/scheduler/scheduler.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/scheduler.c.i
.PHONY : lib/scheduler/scheduler.c.i

lib/scheduler/scheduler.s: lib/scheduler/scheduler.c.s

.PHONY : lib/scheduler/scheduler.s

# target to generate assembly for a file
lib/scheduler/scheduler.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/scheduler.c.s
.PHONY : lib/scheduler/scheduler.c.s

lib/scheduler/switch_context.o: lib/scheduler/switch_context.S.o

.PHONY : lib/scheduler/switch_context.o

# target to build an object file
lib/scheduler/switch_context.S.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/switch_context.S.o
.PHONY : lib/scheduler/switch_context.S.o

lib/scheduler/switch_context.i: lib/scheduler/switch_context.S.i

.PHONY : lib/scheduler/switch_context.i

# target to preprocess a source file
lib/scheduler/switch_context.S.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/switch_context.S.i
.PHONY : lib/scheduler/switch_context.S.i

lib/scheduler/switch_context.s: lib/scheduler/switch_context.S.s

.PHONY : lib/scheduler/switch_context.s

# target to generate assembly for a file
lib/scheduler/switch_context.S.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/scheduler/switch_context.S.s
.PHONY : lib/scheduler/switch_context.S.s

lib/structures/fibonacci_heap.o: lib/structures/fibonacci_heap.c.o

.PHONY : lib/structures/fibonacci_heap.o

# target to build an object file
lib/structures/fibonacci_heap.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/fibonacci_heap.c.o
.PHONY : lib/structures/fibonacci_heap.c.o

lib/structures/fibonacci_heap.i: lib/structures/fibonacci_heap.c.i

.PHONY : lib/structures/fibonacci_heap.i

# target to preprocess a source file
lib/structures/fibonacci_heap.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/fibonacci_heap.c.i
.PHONY : lib/structures/fibonacci_heap.c.i

lib/structures/fibonacci_heap.s: lib/structures/fibonacci_heap.c.s

.PHONY : lib/structures/fibonacci_heap.s

# target to generate assembly for a file
lib/structures/fibonacci_heap.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/fibonacci_heap.c.s
.PHONY : lib/structures/fibonacci_heap.c.s

lib/structures/hash_map.o: lib/structures/hash_map.c.o

.PHONY : lib/structures/hash_map.o

# target to build an object file
lib/structures/hash_map.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/hash_map.c.o
.PHONY : lib/structures/hash_map.c.o

lib/structures/hash_map.i: lib/structures/hash_map.c.i

.PHONY : lib/structures/hash_map.i

# target to preprocess a source file
lib/structures/hash_map.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/hash_map.c.i
.PHONY : lib/structures/hash_map.c.i

lib/structures/hash_map.s: lib/structures/hash_map.c.s

.PHONY : lib/structures/hash_map.s

# target to generate assembly for a file
lib/structures/hash_map.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/hash_map.c.s
.PHONY : lib/structures/hash_map.c.s

lib/structures/lf_stack.o: lib/structures/lf_stack.c.o

.PHONY : lib/structures/lf_stack.o

# target to build an object file
lib/structures/lf_stack.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/lf_stack.c.o
.PHONY : lib/structures/lf_stack.c.o

lib/structures/lf_stack.i: lib/structures/lf_stack.c.i

.PHONY : lib/structures/lf_stack.i

# target to preprocess a source file
lib/structures/lf_stack.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/lf_stack.c.i
.PHONY : lib/structures/lf_stack.c.i

lib/structures/lf_stack.s: lib/structures/lf_stack.c.s

.PHONY : lib/structures/lf_stack.s

# target to generate assembly for a file
lib/structures/lf_stack.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/lf_stack.c.s
.PHONY : lib/structures/lf_stack.c.s

lib/structures/list.o: lib/structures/list.c.o

.PHONY : lib/structures/list.o

# target to build an object file
lib/structures/list.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/list.c.o
.PHONY : lib/structures/list.c.o

lib/structures/list.i: lib/structures/list.c.i

.PHONY : lib/structures/list.i

# target to preprocess a source file
lib/structures/list.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/list.c.i
.PHONY : lib/structures/list.c.i

lib/structures/list.s: lib/structures/list.c.s

.PHONY : lib/structures/list.s

# target to generate assembly for a file
lib/structures/list.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/list.c.s
.PHONY : lib/structures/list.c.s

lib/structures/rb_tree.o: lib/structures/rb_tree.c.o

.PHONY : lib/structures/rb_tree.o

# target to build an object file
lib/structures/rb_tree.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/rb_tree.c.o
.PHONY : lib/structures/rb_tree.c.o

lib/structures/rb_tree.i: lib/structures/rb_tree.c.i

.PHONY : lib/structures/rb_tree.i

# target to preprocess a source file
lib/structures/rb_tree.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/rb_tree.c.i
.PHONY : lib/structures/rb_tree.c.i

lib/structures/rb_tree.s: lib/structures/rb_tree.c.s

.PHONY : lib/structures/rb_tree.s

# target to generate assembly for a file
lib/structures/rb_tree.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/rb_tree.c.s
.PHONY : lib/structures/rb_tree.c.s

lib/structures/splay_tree.o: lib/structures/splay_tree.c.o

.PHONY : lib/structures/splay_tree.o

# target to build an object file
lib/structures/splay_tree.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/splay_tree.c.o
.PHONY : lib/structures/splay_tree.c.o

lib/structures/splay_tree.i: lib/structures/splay_tree.c.i

.PHONY : lib/structures/splay_tree.i

# target to preprocess a source file
lib/structures/splay_tree.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/splay_tree.c.i
.PHONY : lib/structures/splay_tree.c.i

lib/structures/splay_tree.s: lib/structures/splay_tree.c.s

.PHONY : lib/structures/splay_tree.s

# target to generate assembly for a file
lib/structures/splay_tree.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/splay_tree.c.s
.PHONY : lib/structures/splay_tree.c.s

lib/structures/thin_heap.o: lib/structures/thin_heap.c.o

.PHONY : lib/structures/thin_heap.o

# target to build an object file
lib/structures/thin_heap.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/thin_heap.c.o
.PHONY : lib/structures/thin_heap.c.o

lib/structures/thin_heap.i: lib/structures/thin_heap.c.i

.PHONY : lib/structures/thin_heap.i

# target to preprocess a source file
lib/structures/thin_heap.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/thin_heap.c.i
.PHONY : lib/structures/thin_heap.c.i

lib/structures/thin_heap.s: lib/structures/thin_heap.c.s

.PHONY : lib/structures/thin_heap.s

# target to generate assembly for a file
lib/structures/thin_heap.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/lib/structures/thin_heap.c.s
.PHONY : lib/structures/thin_heap.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... compiler"
	@echo "... lib/default.o"
	@echo "... lib/default.i"
	@echo "... lib/default.s"
	@echo "... lib/locks/atomics.o"
	@echo "... lib/locks/atomics.i"
	@echo "... lib/locks/atomics.s"
	@echo "... lib/locks/spinlock.o"
	@echo "... lib/locks/spinlock.i"
	@echo "... lib/locks/spinlock.s"
	@echo "... lib/locks/wait_group.o"
	@echo "... lib/locks/wait_group.i"
	@echo "... lib/locks/wait_group.s"
	@echo "... lib/root_lib.o"
	@echo "... lib/root_lib.i"
	@echo "... lib/root_lib.s"
	@echo "... lib/scheduler/context.o"
	@echo "... lib/scheduler/context.i"
	@echo "... lib/scheduler/context.s"
	@echo "... lib/scheduler/coroutine.o"
	@echo "... lib/scheduler/coroutine.i"
	@echo "... lib/scheduler/coroutine.s"
	@echo "... lib/scheduler/fiber.o"
	@echo "... lib/scheduler/fiber.i"
	@echo "... lib/scheduler/fiber.s"
	@echo "... lib/scheduler/local_queues_with_steal_scheduler.o"
	@echo "... lib/scheduler/local_queues_with_steal_scheduler.i"
	@echo "... lib/scheduler/local_queues_with_steal_scheduler.s"
	@echo "... lib/scheduler/manager.o"
	@echo "... lib/scheduler/manager.i"
	@echo "... lib/scheduler/manager.s"
	@echo "... lib/scheduler/scheduler.o"
	@echo "... lib/scheduler/scheduler.i"
	@echo "... lib/scheduler/scheduler.s"
	@echo "... lib/scheduler/switch_context.o"
	@echo "... lib/scheduler/switch_context.i"
	@echo "... lib/scheduler/switch_context.s"
	@echo "... lib/structures/fibonacci_heap.o"
	@echo "... lib/structures/fibonacci_heap.i"
	@echo "... lib/structures/fibonacci_heap.s"
	@echo "... lib/structures/hash_map.o"
	@echo "... lib/structures/hash_map.i"
	@echo "... lib/structures/hash_map.s"
	@echo "... lib/structures/lf_stack.o"
	@echo "... lib/structures/lf_stack.i"
	@echo "... lib/structures/lf_stack.s"
	@echo "... lib/structures/list.o"
	@echo "... lib/structures/list.i"
	@echo "... lib/structures/list.s"
	@echo "... lib/structures/rb_tree.o"
	@echo "... lib/structures/rb_tree.i"
	@echo "... lib/structures/rb_tree.s"
	@echo "... lib/structures/splay_tree.o"
	@echo "... lib/structures/splay_tree.i"
	@echo "... lib/structures/splay_tree.s"
	@echo "... lib/structures/thin_heap.o"
	@echo "... lib/structures/thin_heap.i"
	@echo "... lib/structures/thin_heap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

